version: '3'

services:
  server:
    build: .
    ports:
      - "50051:50051"

  client-old:
    build:
      dockerfile: ../Dockerfile
      context: ./cliente_original
    command: python client.py
    depends_on:
      - server

  client-new:
    build: .
    command: python client_new.py
    depends_on:
      - server